Code for operations of the singlyl linked list
AmitKarnam/Data-Structures pull request #6
Opened 2020-10-01 12:05 UTC by Ramjonchhen

Code contains insertion/deletion at the head/tail position, in the nth position and displaying of the singly linked list.

2020-10-02 04:34 UTC, Ramjonchhen commented
Done with Code of Doubly Linked List.

2020-10-03 04:48 UTC, AmitKarnam requested changes
@Ramjonchhen Can you write functions for insertion , deletion and displaying of a linked list using only 3 functions. Please delete functions such as deleteAtTail() or deleteAtHead().

Syntactical error present in line 79 ( ' { ' missing after function definition )   

Please include sample Output. Refer to array.c  on how to present your code for a PR.

2020-10-03 09:06 UTC, Ramjonchhen commented
Sure Looking forward to make those changes.

2020-10-04 06:28 UTC, AmitKarnam approved these changes

2020-10-04 06:30 UTC, merged